language: "en-US"
reviews:
  profile: "chill"
  path_instructions:
    - path: "**"
      instructions: |
        You are reviewing "Erion Ember", an LLM Semantic Cache implementation using Bun, Fastify, and Redis.

        Please focus on the following key areas:
        1. **Performance & Caching Logic**: Ensure efficient usage of `hnswlib-node` and Redis. Watch for latency bottlenecks.
        2. **Bun & Fastify**: Ensure compatibility with the Bun runtime and Fastify best practices.
        3. **Docker**: Verify `Dockerfile` and `docker-compose.yml` changes, especially for native dependencies.
        4. **Testing**: Check for `bun test` coverage and K6 benchmark considerations.
